### PR TITLE
Sanitize email option

### PR DESCRIPTION
**Pull request by ttodua**
- adding necessary option to avoid spam/duplicate and achieve unique account registration per one google account

### CODE REVIEW

**Comment by tarecord** [comment]
Hey @ttodua this is a great idea. Instead of making this a setting, should we just sanitize emails by default?

Are there any situations in which the site administrator would _not_ want emails to be sanitized?

**Comment by ttodua** [comment]
actually, there shouldn't be a case in normal situation. Imho, one account (of google) means one person and should be samely treated by website. there was another route too - when getting google-acc ID upon signin, that is also unique, but associating different emails to one id is more cumbersome, then just filtering out extra chars from email to sanitize down to original google email. So, i think it will be quite ok if we will not have an option at all and just make sanitization default. However, as always, I am 100% toward using hooks - let everything was hookable/customizable by user/coder. so, the method should be like:

```
	public function check_to_sanitize( $email ) {
		return apply_filters ( 'siwg_google_email_sanitization', true )  ? Sign_In_With_Google_Utility::sanitize_google_email( $email ) : return $email;
	}

```

**Comment by ttodua** [comment]
any thoughts when you might have time for this plugin to merge PRs?

**Comment by tarecord** [comment]
@ttodua I've actually given this functionality some thought, and while I agree that sanitization is good. Maybe this is being too heavy-handed for users?

Consider the case where an agency is using a shared google account to do some testing and they've set up multiple users based on Google's ability to set aliases with `+`. They might have users such as `shared+developer@gmail.com`, `shared+designer@gmail.com`, and `shared+quality_assurance@gmail.com`. Adding this sanitization would cause quite a bit of confusion if their workflow has been in use like this for a while.

I don't believe we should sanitize these email variants because I'm sure there are users utilizing them for valid use cases.

What do you think?

**Comment by ttodua** [comment]
Tanner, to be honest, I will say - I am fan/advocate of customization capabilities and more opponent of any one-side enforced functionality (on behalf of user). That was the reason, i've exposed this as an option - whoever wants that way, will check the checkbox. By default, you can leave the checkbox unchecked (thus, leaving the default functionality as it was before). but option will be there.

**Comment by ttodua** [comment]
just as a comment, after re-reading your comment, maybe we are slightly on different thoughts, lmk if i correctly understood: 
- aliases (`+`) are not creating separate accounts/usernames/passwords. they have only 1 purpose to exist - when you send to `someone+a1@..` and `someone+a2@..` , then emails are delivered to same `someone@gmail.com`. I dont think there might anywhere exist an agency, which even share (to start with, none of the firm/agency should share google accounts that way, it's anti-pattern of management) accounts, will have persons separated by aliases. I dont think such case might exist (there might be exceptions) as such separation cant lead to any kind of user/account separations.  I think that the only case where gmail aliases are used, are for the purpose to sign-up on different services with aliases (i.e. when someone sign-ups on sketchy site, which doesnt have unsubscribe, i.e. 'temporary-site.com', s/he use alias like `johndoe+temporarysite@gmail.com` - so when you are bored of spam on that alias, you will just mark that alias as spam or even block it, so you will no longer get emails delivered on that alias)

**Comment by ttodua** [comment]
so, wasnt the option/functionality merged, right?

**Pull request closed without merging**
