### PR TITLE
Change for `google_response` url construction

### PR DESCRIPTION
**Pull request by ttodua**
ability to hook, instead of hardcoded slug

### CODE REVIEW

**Comment by ChrisMKindred** [comment]
I think a better way to handle this would be with a filter allowing you to override the home URL and query param. I would like to avoid bloating the admin with settings as much as possible.

**Comment by ttodua** [comment]
Is it possible to have an 'advanced' button (or 'expand' or whatever), and clicking after that these settings were  visible? 
the point of plugin/extension is to offer wordpress users ability to avoid 'using codes' and hiring programmer to hardcode something, so, things were manageable from dashboard. at least, I am way much opponent of hardcoding things and more advocate of providing users capability to customize things as they want, and not to forbid.
however, as you wish. I will still go with my fork.

**Comment by ttodua** [comment]
> provide the best experience for users and developers looking to provide customizations for their use-cases.
actually, this is in opposite in our case, as our client(s) can't set on their own and have to ask us (programmers) every time to manually change (which is what we highly distracts), but anyway, it's your plugin and you decide. 
regards

**Comment by ttodua** [comment]
also, another approach which we used in our old plugins, was to check like 
```
if (apply_filters('ZYK_show_extended_settings', false)) { ?> 
     
      <input .........   />
<?php
}
```

to show some form fields in case there was a constant defined or filter (i.e. `ZYK_show_extended_settings`) set to true.  that might be a possible route in such cases too.

**Pull request closed without merging**
